version: '3.8'

services:
  backend:
    build: ./backend
    container_name: pos-backend
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: pos-frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:latest
    container_name: pos-db
    environment:
      - POSTGRES_DB=yourdb
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: pos-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
