{
  "name": "bms-pos-setup",
  "version": "1.0.0",
  "description": "Setup script for Business Management System (Odoo) and Point of Sale (OpenBravo POS)",
  "main": "index.js",
  "scripts": {
    "start": "bash setup_bms_pos.sh",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/allyelvis/bms-pos-setup.git"
  },
  "keywords": [
    "odoo",
    "openbravo",
    "pos",
    "setup",
    "script"
  ],
  "author": "Ally Elvis Nzeyimana",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/allyelvis/bms-pos-setup/issues"
  },
  "homepage": "https://github.com/allyelvis/bms-pos-setup#readme",
  "dependencies": {
    "some-dependency": "^1.0.0"
  }
}
name: Publish Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Publish package to GitHub Package Registry
      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --access public